---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: homelab-core
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/ucore-minimal
image-version: stable

modules:
  - from-file: common-modules.yml
