---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: blue-core
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/ucore-minimal
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /
      - source: usr
        destination: /usr

  - type: dnf
    repos:
      copr:
        - atim/starship
    install:
      packages:
        - starship
        - fish
        - bat
        - btop
        - fastfetch
        - neovim
        - helix
        - just
        - distrobox
        - nfs-utils
        - gcc
        - zoxide

  - type: script
    scripts:
      - install-eza.sh

  - type: chezmoi
    repository: https://github.com/rjrobert/dotfiles

  - type: systemd
    system:
      enabled:
        - podman.socket
        - podman-auto-update.timer
        - cockpit.service
        - var-truenas.mount
        - bootc-fetch-apply-updates.timer
      disabled:
        - rpm-ostreed-automatic.timer

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
